// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhQPHfuFkR1JIq0Xr1Qz09kin_50o68hg',
    appId: '1:594246605943:web:d3c9c5f85cdd942f227a72',
    messagingSenderId: '594246605943',
    projectId: 'cloud-d7421',
    authDomain: 'cloud-d7421.firebaseapp.com',
    storageBucket: 'cloud-d7421.firebasestorage.app',
    measurementId: 'G-K51SKZ0DB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKUgcWf7R2MLKi91dIVewBB4c9Id9xezY',
    appId: '1:594246605943:android:35c85e69c000849c227a72',
    messagingSenderId: '594246605943',
    projectId: 'cloud-d7421',
    storageBucket: 'cloud-d7421.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwN-n5PurQ_YyjjgiCcFmu7uXVCa1tAk8',
    appId: '1:594246605943:ios:6f84497d794deadb227a72',
    messagingSenderId: '594246605943',
    projectId: 'cloud-d7421',
    storageBucket: 'cloud-d7421.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwN-n5PurQ_YyjjgiCcFmu7uXVCa1tAk8',
    appId: '1:594246605943:ios:6f84497d794deadb227a72',
    messagingSenderId: '594246605943',
    projectId: 'cloud-d7421',
    storageBucket: 'cloud-d7421.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessaging',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhQPHfuFkR1JIq0Xr1Qz09kin_50o68hg',
    appId: '1:594246605943:web:ac4be586ff137d08227a72',
    messagingSenderId: '594246605943',
    projectId: 'cloud-d7421',
    authDomain: 'cloud-d7421.firebaseapp.com',
    storageBucket: 'cloud-d7421.firebasestorage.app',
    measurementId: 'G-C04CC89H5Q',
  );

}